source "http://rubygems.org"

gem "rake", "~> 0.9"
gem "cucumber", "~> 1.0"
gem "rspec", "~> 2.0"
gem "capybara", "~> 2.1.0"
gem "site_prism", "~> 2.0"
gem "activesupport", "~> 3.2"
gem "tzinfo", "~> 0.3.33"
gem "headless", "~> 1.0.1"
gem "selenium-webdriver", "~> 2.0"
