defaults: &execution_defaults
  default_config: local_env_kr
local_env_kr:
  <<: *execution_defaults
  # site name
  country_site: Korea
  #capybara settings
  default_wait_time: 5
  #urls
  korea_site_root: http://kr.local.solas.britishcouncil.net:8080/en
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
local_env_jp:
  <<: *execution_defaults
  # site name
  country_site: Japan
  #capybara settings
  default_wait_time: 5
  #urls
  korea_site_root: http://jp.local.solas.britishcouncil.net:8080/en
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
local_env_gr:
  <<: *execution_defaults
  # site name
  country_site: Greece
  #capybara settings
  default_wait_time: 5
  #urls
  korea_site_root: http://gr.local.solas.britishcouncil.net:8080/en
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
local_env_training:
  <<: *execution_defaults
  # site name
  country_site: Training
  #capybara settings
  default_wait_time: 5
  #urls
  korea_site_root: http://training.local.solas.britishcouncil.net:8080/en
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
test_env_kr:
  <<: *execution_defaults
  # site name
  country_site: Korea
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://kr.test.solas.britishcouncil.net/en
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
test_env_jp:
  <<: *execution_defaults
  # site name
  country_site: Japan
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://jp.test.solas.britishcouncil.net/en
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
test_env_training:
  <<: *execution_defaults
  # site name
  country_site: Training
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://training.test.solas.britishcouncil.net/en
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
test_env_greece:
  <<: *execution_defaults
  # site name
  country_site: Greece
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://gr.test.solas.britishcouncil.net/en
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
stage_env_kr:
  <<: *execution_defaults
  # site name
  country_site: Korea
  #capybara settings
  default_wait_time: 5
  #urls
  korea_site_root: http://kr.stage.solas.britishcouncil.net/en
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
stage_env_jp:
  <<: *execution_defaults
  # site name
  country_site: Japan
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://jp.stage.solas.britishcouncil.net/en
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'Password_1'
  author_username: 'test.author'
  author_password: 'Password_1'
  manager_username: 'test.manager'
  manager_password: 'Password_1'
  producer_username: 'test.producer'
  producer_password: 'Password_1'
stage_env_training:
  <<: *execution_defaults
  # site name
  country_site: Training
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://training.stage.solas.britishcouncil.net/en
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'Password_1'
  author_username: 'test.author'
  author_password: 'Password_1'
  manager_username: 'test.manager'
  manager_password: 'Password_1'
  producer_username: 'test.producer'
  producer_password: 'Password_1'
stage_env_greece:
  <<: *execution_defaults
  # site name
  country_site: Training
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://training.stage.solas.britishcouncil.net/en
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'Password_1'
  author_username: 'test.author'
  author_password: 'Password_1'
  manager_username: 'test.manager'
  manager_password: 'Password_1'
  producer_username: 'test.producer'
  producer_password: 'Password_1'
live_env_kr:
  <<: *execution_defaults
  # site name
  country_site: Korea
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://kr.live.solas.britishcouncil.net/en
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'Password_1'
  author_username: 'test.author'
  author_password: 'Password_1'
  manager_username: 'test.manager'
  manager_password: 'Password_1'
  producer_username: 'test.producer'
  producer_password: 'Password_1'
live_env_jp:
  <<: *execution_defaults
  # site name
  country_site: Japan
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://jp.live.solas.britishcouncil.net/en
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'Password_1'
  author_username: 'test.author'
  author_password: 'Password_1'
  manager_username: 'test.manager'
  manager_password: 'Password_1'
  producer_username: 'test.producer'
  producer_password: 'Password_1'
live_env_training:
  <<: *execution_defaults
  # site name
  country_site: Training
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://training.live.solas.britishcouncil.net/en
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'Password_1'
  author_username: 'test.author'
  author_password: 'Password_1'
  manager_username: 'test.manager'
  manager_password: 'Password_1'
  producer_username: 'test.producer'
  producer_password: 'Password_1'
live_env_greece:
  <<: *execution_defaults
  # site name
  country_site: Greece
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://gr.live.solas.britishcouncil.net/en
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'Password_1'
  author_username: 'test.author'
  author_password: 'Password_1'
  manager_username: 'test.manager'
  manager_password: 'Password_1'
  producer_username: 'test.producer'
  producer_password: 'Password_1'