defaults: &execution_defaults
  default_config: local_env_eg
#korea config
local_env_kr:
  <<: *execution_defaults
  # site name
  country_site: Korea
  #capybara settings
  default_wait_time: 8
  #urls
  korea_site_root: http://kr.local.solas.britishcouncil.net:8080/en
  korea_site_root_without_en: http://kr.local.solas.britishcouncil.net:8080
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
test_env_kr:
  <<: *execution_defaults
  # site name
  country_site: Korea
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://kr.test.solas.britishcouncil.net/en
  korea_site_root_without_en: http://kr.test.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'ZBjewW2zVR'
  author_username: 'test.author'
  author_password: 'ZBjewW2zVR'
  manager_username: 'test.manager'
  manager_password: 'ZBjewW2zVR'
  producer_username: 'test.producer'
  producer_password: 'ZBjewW2zVR'
stage_env_kr:
  <<: *execution_defaults
  # site name
  country_site: Korea
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://kr.stage.solas.britishcouncil.net/en
  korea_site_root_without_en: http://kr.stage.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'ZBjewW2zVR'
  author_username: 'test.author'
  author_password: 'ZBjewW2zVR'
  manager_username: 'test.manager'
  manager_password: 'ZBjewW2zVR'
  producer_username: 'test.producer'
  producer_password: 'ZBjewW2zVR'
live_env_kr:
  <<: *execution_defaults
  # site name
  country_site: Korea
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://kr.live.solas.britishcouncil.net/en
  korea_site_root_without_en: http://kr.live.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'Password_1'
  author_username: 'test.author'
  author_password: 'Password_1'
  manager_username: 'test.manager'
  manager_password: 'Password_1'
  producer_username: 'test.producer'
  producer_password: 'Password_1'
#japan config
local_env_jp:
  <<: *execution_defaults
  # site name
  country_site: Japan
  #capybara settings
  default_wait_time: 8
  #urls
  korea_site_root: http://jp.local.solas.britishcouncil.net:8080/en
  korea_site_root_without_en: http://jp.local.solas.britishcouncil.net:8080
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
test_env_jp:
  <<: *execution_defaults
  # site name
  country_site: Japan
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://jp.test.solas.britishcouncil.net/en
  korea_site_root_without_en: http://jp.test.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
stage_env_jp:
  <<: *execution_defaults
  # site name
  country_site: Japan
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://jp.stage.solas.britishcouncil.net/en
  korea_site_root_without_en: http://jp.stage.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'ZBjewW2zVR'
  author_username: 'test.author'
  author_password: 'ZBjewW2zVR'
  manager_username: 'test.manager'
  manager_password: 'ZBjewW2zVR'
  producer_username: 'test.producer'
  producer_password: 'ZBjewW2zVR'
live_env_jp:
  <<: *execution_defaults
  # site name
  country_site: Japan
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://jp.live.solas.britishcouncil.net/en
  korea_site_root_without_en: http://jp.live.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'Password_1'
  author_username: 'test.author'
  author_password: 'Password_1'
  manager_username: 'test.manager'
  manager_password: 'Password_1'
  producer_username: 'test.producer'
  producer_password: 'Password_1'
#greece config
local_env_gr:
  <<: *execution_defaults
  # site name
  country_site: Greece
  #capybara settings
  default_wait_time: 8
  #urls
  korea_site_root: http://gr.local.solas.britishcouncil.net:8080/en
  korea_site_root_without_en: http://gr.local.solas.britishcouncil.net:8080
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
test_env_gr:
  <<: *execution_defaults
  # site name
  country_site: Greece
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://gr.test.solas.britishcouncil.net/en
  korea_site_root_without_en: http://gr.test.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'ZBjewW2zVR'
  author_username: 'test.author'
  author_password: 'ZBjewW2zVR'
  manager_username: 'test.manager'
  manager_password: 'ZBjewW2zVR'
  producer_username: 'test.producer'
  producer_password: 'ZBjewW2zVR'
stage_env_gr:
  <<: *execution_defaults
  # site name
  country_site: Training
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://gr.stage.solas.britishcouncil.net/en
  korea_site_root_without_en: http://gr.stage.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'ZBjewW2zVR'
  author_username: 'test.author'
  author_password: 'ZBjewW2zVR'
  manager_username: 'test.manager'
  manager_password: 'ZBjewW2zVR'
  producer_username: 'test.producer'
  producer_password: 'ZBjewW2zVR'
live_env_gr:
  <<: *execution_defaults
  # site name
  country_site: Greece
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://gr.live.solas.britishcouncil.net/en
  korea_site_root_without_en: http://gr.live.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'Password_1'
  author_username: 'test.author'
  author_password: 'Password_1'
  manager_username: 'test.manager'
  manager_password: 'Password_1'
  producer_username: 'test.producer'
  producer_password: 'Password_1'
#training config
local_env_training:
  <<: *execution_defaults
  # site name
  country_site: Training
  #capybara settings
  default_wait_time: 8
  #urls
  korea_site_root: http://training.local.solas.britishcouncil.net:8080/en
  korea_site_root_without_en: http://training.local.solas.britishcouncil.net:8080
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
test_env_training:
  <<: *execution_defaults
  # site name
  country_site: Training
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://training.test.solas.britishcouncil.net/en
  korea_site_root_without_en: http://training.test.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
stage_env_training:
  <<: *execution_defaults
  # site name
  country_site: Training
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://training.stage.solas.britishcouncil.net/en
  korea_site_root_without_en: http://training.stage.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'ZBjewW2zVR'
  author_username: 'test.author'
  author_password: 'ZBjewW2zVR'
  manager_username: 'test.manager'
  manager_password: 'ZBjewW2zVR'
  producer_username: 'test.producer'
  producer_password: 'ZBjewW2zVR'
live_env_training:
  <<: *execution_defaults
  # site name
  country_site: Training
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://training.live.solas.britishcouncil.net/en
  korea_site_root_without_en: http://training.live.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'Password_1'
  author_username: 'test.author'
  author_password: 'Password_1'
  manager_username: 'test.manager'
  manager_password: 'Password_1'
  producer_username: 'test.producer'
  producer_password: 'Password_1'
local_env_eg:
  <<: *execution_defaults
  # site name
  country_site: Egypt
  #capybara settings
  default_wait_time: 8
  #urls
  korea_site_root: http://eg.local.solas.britishcouncil.net:8080/en
  korea_site_root_without_en: http://eg.local.solas.britishcouncil.net:8080
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
test_env_eg:
  <<: *execution_defaults
  # site name
  country_site: Egypt
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://eg.test.solas.britishcouncil.net/en
  korea_site_root_without_en: http://eg.test.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'ZBjewW2zVR'
  author_username: 'test.author'
  author_password: 'ZBjewW2zVR'
  manager_username: 'test.manager'
  manager_password: 'ZBjewW2zVR'
  producer_username: 'test.producer'
  producer_password: 'ZBjewW2zVR'
stage_env_eg:
  <<: *execution_defaults
  # site name
  country_site: Egypt
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://eg.stage.solas.britishcouncil.net/en
  korea_site_root_without_en: http://training.stage.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'ZBjewW2zVR'
  author_username: 'test.author'
  author_password: 'ZBjewW2zVR'
  manager_username: 'test.manager'
  manager_password: 'ZBjewW2zVR'
  producer_username: 'test.producer'
  producer_password: 'ZBjewW2zVR'
live_env_eg:
  <<: *execution_defaults
  # site name
  country_site: Egypt
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://eg.live.solas.britishcouncil.net/en
  korea_site_root_without_en: http://eg.live.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'Password_1'
  author_username: 'test.author'
  author_password: 'Password_1'
  manager_username: 'test.manager'
  manager_password: 'Password_1'
  producer_username: 'test.producer'
  producer_password: 'Password_1'
local_env_pl:
  <<: *execution_defaults
  # site name
  country_site: Poland
  #capybara settings
  default_wait_time: 8
  #urls
  korea_site_root: http://pl.local.solas.britishcouncil.net:8080/en
  korea_site_root_without_en: http://pl.local.solas.britishcouncil.net:8080
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
test_env_pl:
  <<: *execution_defaults
  # site name
  country_site: Poland
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://pl.test.solas.britishcouncil.net/en
  korea_site_root_without_en: http://pl.test.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'ZBjewW2zVR'
  author_username: 'test.author'
  author_password: 'ZBjewW2zVR'
  manager_username: 'test.manager'
  manager_password: 'ZBjewW2zVR'
  producer_username: 'test.producer'
  producer_password: 'ZBjewW2zVR'
stage_env_pl:
  <<: *execution_defaults
  # site name
  country_site: Poland
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://pl.stage.solas.britishcouncil.net/en
  korea_site_root_without_en: http://pl.stage.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'ZBjewW2zVR'
  author_username: 'test.author'
  author_password: 'ZBjewW2zVR'
  manager_username: 'test.manager'
  manager_password: 'ZBjewW2zVR'
  producer_username: 'test.producer'
  producer_password: 'ZBjewW2zVR'
live_env_pl:
  <<: *execution_defaults
  # site name
  country_site: Poland
  #capybara settings
  default_wait_time: 30
  #urls
  korea_site_root: http://pl.live.solas.britishcouncil.net/en
  korea_site_root_without_en: http://pl.live.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'Password_1'
  author_username: 'test.author'
  author_password: 'Password_1'
  manager_username: 'test.manager'
  manager_password: 'Password_1'
  producer_username: 'test.producer'
  producer_password: 'Password_1'
local_env_th:
  <<: *execution_defaults
  # site name
  country_site: Thailand
  #capybara settings
  default_wait_time: 8
  #urls
  korea_site_root: http://th.local.solas.britishcouncil.net:8080/en
  korea_site_root_without_en: http://th.local.solas.britishcouncil.net:8080
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
test_env_th:
  <<: *execution_defaults
  # site name
  country_site: Thailand
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://th.test.solas.britishcouncil.net/en
  korea_site_root_without_en: http://th.test.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'ZBjewW2zVR'
  author_username: 'test.author'
  author_password: 'ZBjewW2zVR'
  manager_username: 'test.manager'
  manager_password: 'ZBjewW2zVR'
  producer_username: 'test.producer'
  producer_password: 'ZBjewW2zVR'
stage_env_th:
  <<: *execution_defaults
  # site name
  country_site: Thailand
  #capybara settings
  default_wait_time: 15
  #urls
  korea_site_root: http://th.stage.solas.britishcouncil.net/en
  korea_site_root_without_en: http://th.stage.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'ZBjewW2zVR'
  author_username: 'test.author'
  author_password: 'ZBjewW2zVR'
  manager_username: 'test.manager'
  manager_password: 'ZBjewW2zVR'
  producer_username: 'test.producer'
  producer_password: 'ZBjewW2zVR'
live_env_th:
  <<: *execution_defaults
  # site name
  country_site: Thailand
  #capybara settings
  default_wait_time: 30
  #urls
  korea_site_root: http://th.live.solas.britishcouncil.net/en
  korea_site_root_without_en: http://pl.live.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'Password_1'
  author_username: 'test.author'
  author_password: 'Password_1'
  manager_username: 'test.manager'
  manager_password: 'Password_1'
  producer_username: 'test.producer'
  producer_password: 'Password_1'