defaults: &execution_defaults
  default_config: test_env_pf

#PF config
test_env_pf:
  <<: *execution_defaults
  # site name
  country_site: PF
  #capybara settings
  default_wait_time: 9
  #urls
  pf_site_root: http://productfinder.qa.britishcouncil.org
  #thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  #image_location: /sites/default/files
  #user details
  admin_username: 'rajkosara'
  admin_password: 'Bhargav123'
  ExamAdmin_username: 'rajkosara'
  ExamAdmin_password: 'Bhargav123'
  CourseAdmin_username: 'rajkosara'
  CourseAdmin_password: 'Bhargav123'
  manager_username: 'rajkosara'
  manager_password: 'Bhargav123'
  