defaults: &execution_defaults
  default_config: local_env_kr
local_env_kr:
  <<: *execution_defaults
  # site name
  country_site: Korea
  #capybara settings
  default_wait_time: 5
  #urls
  korea_site_root: http://kr.local.solas.britishcouncil.net:8080/en
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'test.admin'
  admin_password: 'password'
  author_username: 'test.author'
  author_password: 'password'
  manager_username: 'test.manager'
  manager_password: 'password'
  producer_username: 'test.producer'
  producer_password: 'password'
test_env_kr:
  <<: *execution_defaults
  # site name
  country_site: Korea
  #capybara settings
  default_wait_time: 8
  #urls
  korea_site_root: http://kr.test.solas.britishcouncil.net
  thumbnail_image_location: /sites/default/files/styles/thumbnail/public
  image_location: /sites/default/files
  #user details
  admin_username: 'david.chambers'
  admin_password: 'admin'
